# Generated by Django 5.2.8 on 2025-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HotelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hotel_rooms",
                "indexes": [
                    models.Index(
                        fields=["price_per_night"],
                        name="hotel_rooms_price_p_f6e169_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="hotel_rooms_created_601a5d_idx"
                    ),
                ],
            },
        ),
    ]
