# Generated by Django 5.2.8 on 2025-11-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="hotels.hotelroom",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "indexes": [
                    models.Index(
                        fields=["room", "date_start"],
                        name="bookings_room_id_04db9a_idx",
                    ),
                    models.Index(
                        fields=["date_start", "date_end"],
                        name="bookings_date_st_78d219_idx",
                    ),
                ],
            },
        ),
    ]
